var h=void 0,i=!0,n=null,p=!1,t,v=this;function aa(a,b){var c=a.split("."),d=v;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)!c.length&&b!==h?d[f]=b:d=d[f]?d[f]:d[f]={}}
function x(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ba(a){var b=x(a);return"array"==b||"object"==b&&"number"==typeof a.length}function y(a){return"string"==typeof a}function ca(a){var b=typeof a;return"object"==b&&a!=n||"function"==b}function z(a){return a[da]||(a[da]=++ea)}var da="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ea=0;
function fa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}}function ga(a,b){function c(){}c.prototype=b.prototype;a.hb=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ha(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function ia(a){if(!ja.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(ka,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(la,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ma,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(pa,"&quot;"));return a}var ka=/&/g,la=/</g,ma=/>/g,pa=/\"/g,ja=/[&<>\"]/,qa={};function ra(a){return qa[a]||(qa[a]=(""+a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};var A,sa,ta,ua,va;function wa(){return v.navigator?v.navigator.userAgent:n}function xa(){return v.navigator}ua=ta=sa=A=p;var ya;if(ya=wa()){var za=xa();A=0==ya.indexOf("Opera");sa=!A&&-1!=ya.indexOf("MSIE");ta=!A&&-1!=ya.indexOf("WebKit");ua=!A&&!ta&&"Gecko"==za.product}var Aa=A,B=sa,C=ua,D=ta,Ba=xa();va=-1!=(Ba&&Ba.platform||"").indexOf("Mac");var Ca=!!xa()&&-1!=(xa().appVersion||"").indexOf("X11"),Da;
a:{var Ga="",E;if(Aa&&v.opera)var Ha=v.opera.version,Ga="function"==typeof Ha?Ha():Ha;else if(C?E=/rv\:([^\);]+)(\)|;)/:B?E=/MSIE\s+([^\);]+)(\)|;)/:D&&(E=/WebKit\/(\S+)/),E)var Ia=E.exec(wa()),Ga=Ia?Ia[1]:"";if(B){var Ja,Ka=v.document;Ja=Ka?Ka.documentMode:h;if(Ja>parseFloat(Ga)){Da=""+Ja;break a}}Da=Ga}var La={};
function H(a){var b;if(!(b=La[a])){b=0;for(var c=ha(""+Da).split("."),d=ha(""+a).split("."),f=Math.max(c.length,d.length),e=0;0==b&&e<f;e++){var g=c[e]||"",j=d[e]||"",k=RegExp("(\\d*)(\\D*)","g"),l=RegExp("(\\d*)(\\D*)","g");do{var r=k.exec(g)||["","",""],m=l.exec(j)||["","",""];if(0==r[0].length&&0==m[0].length)break;b=((0==r[1].length?0:parseInt(r[1],10))<(0==m[1].length?0:parseInt(m[1],10))?-1:(0==r[1].length?0:parseInt(r[1],10))>(0==m[1].length?0:parseInt(m[1],10))?1:0)||((0==r[2].length)<(0==
m[2].length)?-1:(0==r[2].length)>(0==m[2].length)?1:0)||(r[2]<m[2]?-1:r[2]>m[2]?1:0)}while(0==b)}b=La[a]=0<=b}return b}var Ma={};function Na(){return Ma[9]||(Ma[9]=B&&!!document.documentMode&&9<=document.documentMode)};annotorious.shape={};annotorious.shape.A={};annotorious.shape.A.mb=function(a,b){this.x=a;this.y=b};annotorious.shape.A.nb=function(a){this.ja=a};annotorious.shape.A.la=function(a,b,c,d){0<c?(this.x=a,this.width=c):(this.x=a+c,this.width=-c);0<d?(this.y=b,this.height=d):(this.y=b+d,this.height=-d)};annotorious.shape.ma=function(a,b){this.type=a;this.e=b};annotorious.shape.j={Pb:"point",v:"rect",X:"polygon"};annotorious.shape.pb={lb:"pixel",Ob:"fraction"};annotorious.shape.Gb=function(a,b,c){if(a.type==annotorious.shape.j.v)return b<a.e.x||c<a.e.y||b>a.e.x+a.e.width||c>a.e.y+a.e.height?p:i;if(a.type==annotorious.shape.j.X){for(var d=p,f=a.e.ja,e=a=a.e.ja.length-1,g=0;g<a;g++){if(f[g].y<c&&f[e].y>=c||f[e].y<c&&f[g].y>=c)f[g].x+(c-f[g].y)/(f[e].y-f[g].y)*(f[e].x-f[g].x)<b&&(d=!d);e=g}return d}return p};
annotorious.shape.size=function(a){return a.type==annotorious.shape.j.v?a.e.width*a.e.height:0};annotorious.shape.Wa=function(a){if(a.type==annotorious.shape.j.v)return a.e;if(a.type==annotorious.shape.j.X){for(var a=a.e.ja,b=a[0].x,c=a[0].x,d=a[0].y,f=a[0].y,e=1;e<a.length;e++)a[e].x>c&&(c=a[e].x),a[e].x<b&&(b=a[e].x),a[e].y>f&&(f=a[e].y),a[e].y<d&&(d=a[e].y);return new annotorious.shape.A.la(b,d,c-b,f-d)}};
annotorious.shape.transform=function(a,b){if(a.type==annotorious.shape.j.v){var c=a.e,d=b({x:c.x,y:c.y}),c=b({x:c.width,y:c.height});return new annotorious.shape.ma(annotorious.shape.j.v,new annotorious.shape.A.la(d.x,d.y,c.x,c.y))}if(a.type==annotorious.shape.j.X){var f=[];I(a.e.ja,function(a){f.push(b(a))});return new annotorious.shape.ma(annotorious.shape.j.X,new annotorious.shape.A.nb(f))}};var J=Array.prototype,Oa=J.indexOf?function(a,b,c){return J.indexOf.call(a,b,c)}:function(a,b,c){c=c==n?0:0>c?Math.max(0,a.length+c):c;if(y(a))return!y(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},I=J.forEach?function(a,b,c){J.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=y(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)};
function Pa(a,b){var c;a:{c=a.length;for(var d=y(a)?a.split(""):a,f=0;f<c;f++)if(f in d&&b.call(h,d[f],f,a)){c=f;break a}c=-1}return 0>c?n:y(a)?a.charAt(c):a[c]}function Qa(a,b){var c=Oa(a,b);0<=c&&J.splice.call(a,c,1)}function Ra(a){return J.concat.apply(J,arguments)}function Sa(a){if("array"==x(a))return Ra(a);for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}function Ta(a,b,c,d){J.splice.apply(a,Ua(arguments,1))}
function Ua(a,b,c){return 2>=arguments.length?J.slice.call(a,b):J.slice.call(a,b,c)}function Va(a,b){J.sort.call(a,b||Wa)}function Wa(a,b){return a>b?1:a<b?-1:0};var Xa,Ya=!B||Na();!C&&!B||B&&Na()||C&&H("1.9.1");B&&H("9");function Za(a){return(a=a.className)&&"function"==typeof a.split?a.split(/\s+/):[]}function $a(a,b){var c=Za(a),d=Ua(arguments,1),f;f=c;for(var e=0,g=0;g<d.length;g++)0<=Oa(f,d[g])||(f.push(d[g]),e++);f=e==d.length;a.className=c.join(" ");return f}function ab(a,b){for(var c=Za(a),d=Ua(arguments,1),f=c,e=0,g=0;g<f.length;g++)0<=Oa(d,f[g])&&(Ta(f,g--,1),e++);a.className=c.join(" ")};function bb(a,b){for(var c in a)b.call(h,a[c],c,a)}var cb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function mb(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<cb.length;e++)c=cb[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function nb(a,b){bb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in ob?a.setAttribute(ob[d],b):0==d.lastIndexOf("aria-",0)?a.setAttribute(d,b):a[d]=b})}var ob={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function pb(a,b,c){var d=arguments,f=document,e=d[0],g=d[1];if(!Ya&&g&&(g.name||g.type)){e=["<",e];g.name&&e.push(' name="',ia(g.name),'"');if(g.type){e.push(' type="',ia(g.type),'"');var j={};mb(j,g);g=j;delete g.type}e.push(">");e=e.join("")}e=f.createElement(e);g&&(y(g)?e.className=g:"array"==x(g)?$a.apply(n,[e].concat(g)):nb(e,g));2<d.length&&qb(f,e,d);return e}
function qb(a,b,c){function d(c){c&&b.appendChild(y(c)?a.createTextNode(c):c)}for(var f=2;f<c.length;f++){var e=c[f];ba(e)&&!(ca(e)&&0<e.nodeType)?I(rb(e)?Sa(e):e,d):d(e)}}function sb(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)}function tb(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function rb(a){if(a&&"number"==typeof a.length){if(ca(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==x(a))return"function"==typeof a.item}return p}function K(a){this.va=a||v.document||document}K.prototype.createElement=function(a){return this.va.createElement(a)};K.prototype.createTextNode=function(a){return this.va.createTextNode(a)};K.prototype.appendChild=function(a,b){a.appendChild(b)};K.prototype.contains=tb;function ub(a,b){var c=(Xa||(Xa=new K)).createElement("DIV");c.innerHTML=a(b||vb,h,h);if(1==c.childNodes.length){var d=c.firstChild;if(1==d.nodeType)return d}return c}var vb={};!B||Na();var wb=!B||Na(),xb=B&&!H("8");!D||H("528");C&&H("1.9b")||B&&H("8")||Aa&&H("9.5")||D&&H("528");!C||H("8");function yb(){}yb.prototype.Va=p;yb.prototype.aa=function(){this.Va||(this.Va=i,this.ba())};yb.prototype.ba=function(){this.Ab&&zb.apply(n,this.Ab)};function zb(a){for(var b=0,c=arguments.length;b<c;++b){var d=arguments[b];ba(d)?zb.apply(n,d):d&&"function"==typeof d.aa&&d.aa()}};function L(a,b){this.type=a;this.currentTarget=this.target=b}ga(L,yb);L.prototype.ba=function(){delete this.type;delete this.target;delete this.currentTarget};L.prototype.za=p;L.prototype.gb=i;L.prototype.preventDefault=function(){this.gb=p};function Ab(a){Ab[" "](a);return a}Ab[" "]=function(){};function M(a,b){a&&this.K(a,b)}ga(M,L);t=M.prototype;t.target=n;t.relatedTarget=n;t.offsetX=0;t.offsetY=0;t.clientX=0;t.clientY=0;t.screenX=0;t.screenY=0;t.button=0;t.keyCode=0;t.charCode=0;t.ctrlKey=p;t.altKey=p;t.shiftKey=p;t.metaKey=p;t.r=n;
t.K=function(a,b){var c=this.type=a.type;L.call(this,c);this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(C){var f;a:{try{Ab(d.nodeName);f=i;break a}catch(e){}f=p}f||(d=n)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=D||a.offsetX!==h?a.offsetX:a.layerX;this.offsetY=D||a.offsetY!==h?a.offsetY:a.layerY;this.clientX=a.clientX!==h?a.clientX:a.pageX;this.clientY=a.clientY!==h?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;this.r=a;delete this.gb;delete this.za};t.preventDefault=function(){M.hb.preventDefault.call(this);var a=this.r;if(a.preventDefault)a.preventDefault();else if(a.returnValue=p,xb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
t.ba=function(){M.hb.ba.call(this);this.relatedTarget=this.currentTarget=this.target=this.r=n};function Bb(){}var Cb=0;t=Bb.prototype;t.key=0;t.M=p;t.Ua=p;t.K=function(a,b,c,d,f,e){if("function"==x(a))this.ab=i;else if(a&&a.handleEvent&&"function"==x(a.handleEvent))this.ab=p;else throw Error("Invalid listener argument");this.fa=a;this.fb=b;this.src=c;this.type=d;this.capture=!!f;this.Ya=e;this.Ua=p;this.key=++Cb;this.M=p};t.handleEvent=function(a){return this.ab?this.fa.call(this.Ya||this.src,a):this.fa.handleEvent.call(this.fa,a)};var N={},O={},P={},Q={};
function R(a,b,c,d,f){if(b){if("array"==x(b)){for(var e=0;e<b.length;e++)R(a,b[e],c,d,f);return n}var d=!!d,g=O;b in g||(g[b]={t:0,F:0});g=g[b];d in g||(g[d]={t:0,F:0},g.t++);var g=g[d],j=z(a),k;g.F++;if(g[j]){k=g[j];for(e=0;e<k.length;e++)if(g=k[e],g.fa==c&&g.Ya==f){if(g.M)break;return k[e].key}}else k=g[j]=[],g.t++;e=Db();e.src=a;g=new Bb;g.K(c,e,a,b,d,f);c=g.key;e.key=c;k.push(g);N[c]=g;P[j]||(P[j]=[]);P[j].push(g);a.addEventListener?(a==v||!a.zb)&&a.addEventListener(b,e,d):a.attachEvent(b in Q?
Q[b]:Q[b]="on"+b,e);return c}throw Error("Invalid event type");}function Db(){var a=Eb,b=wb?function(c){return a.call(b.src,b.key,c)}:function(c){c=a.call(b.src,b.key,c);if(!c)return c};return b}
function U(a){if(N[a]){var b=N[a];if(!b.M){var c=b.src,d=b.type,f=b.fb,e=b.capture;c.removeEventListener?(c==v||!c.zb)&&c.removeEventListener(d,f,e):c.detachEvent&&c.detachEvent(d in Q?Q[d]:Q[d]="on"+d,f);c=z(c);f=O[d][e][c];if(P[c]){var g=P[c];Qa(g,b);0==g.length&&delete P[c]}b.M=i;f.cb=i;Fb(d,e,c,f);delete N[a]}}}
function Fb(a,b,c,d){if(!d.ga&&d.cb){for(var f=0,e=0;f<d.length;f++)d[f].M?d[f].fb.src=n:(f!=e&&(d[e]=d[f]),e++);d.length=e;d.cb=p;0==e&&(delete O[a][b][c],O[a][b].t--,0==O[a][b].t&&(delete O[a][b],O[a].t--),0==O[a].t&&delete O[a])}}function Gb(a,b,c,d,f){var e=1,b=z(b);if(a[b]){a.F--;a=a[b];a.ga?a.ga++:a.ga=1;try{for(var g=a.length,j=0;j<g;j++){var k=a[j];k&&!k.M&&(e&=Hb(k,f)!==p)}}finally{a.ga--,Fb(c,d,b,a)}}return Boolean(e)}function Hb(a,b){var c=a.handleEvent(b);a.Ua&&U(a.key);return c}
function Eb(a,b){if(!N[a])return i;var c=N[a],d=c.type,f=O;if(!(d in f))return i;var f=f[d],e,g;if(!wb){var j;if(!(j=b))a:{j=["window","event"];for(var k=v;e=j.shift();)if(k[e]!=n)k=k[e];else{j=n;break a}j=k}e=j;j=i in f;k=p in f;if(j){if(0>e.keyCode||e.returnValue!=h)return i;a:{var l=p;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(r){l=i}if(l||e.returnValue==h)e.returnValue=i}}l=new M;l.K(e,this);e=i;try{if(j){for(var m=[],q=l.currentTarget;q;q=q.parentNode)m.push(q);g=f[i];g.F=g.t;for(var u=m.length-
1;!l.za&&0<=u&&g.F;u--)l.currentTarget=m[u],e&=Gb(g,m[u],d,i,l);if(k){g=f[p];g.F=g.t;for(u=0;!l.za&&u<m.length&&g.F;u++)l.currentTarget=m[u],e&=Gb(g,m[u],d,p,l)}}else e=Hb(c,l)}finally{m&&(m.length=0),l.aa()}return e}d=new M(b,this);try{e=Hb(c,d)}finally{d.aa()}return e};function V(){return i};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var Ib=function(){function a(a,c){if(!a)return[];if(a.constructor==Array)return a;if(!y(a))return[a];if(y(c)&&(c=y(c)?document.getElementById(c):c,!c))return[];var c=c||document,e=c.ownerDocument||c.documentElement;S=c.contentType&&"application/xml"==c.contentType||Aa&&(c.doctype||"[object XMLDocument]"==e.toString())||!!e&&(B?e.xml:c.xmlVersion||e.xmlVersion);return(e=d(a)(c))&&e.ha?e:b(e)}function b(a){if(a&&a.ha)return a;var b=[];if(!a||!a.length)return b;a[0]&&b.push(a[0]);if(2>a.length)return b;
F++;if(B&&S){var c=F+"";a[0].setAttribute("_zipIdx",c);for(var d=1,e;e=a[d];d++)a[d].getAttribute("_zipIdx")!=c&&b.push(e),e.setAttribute("_zipIdx",c)}else if(B&&a.yb)try{for(d=1;e=a[d];d++)na(e)&&b.push(e)}catch(f){}else{a[0]&&(a[0]._zipIdx=F);for(d=1;e=a[d];d++)a[d]._zipIdx!=F&&b.push(e),e._zipIdx=F}return b}function c(a,b){if(!b)return 1;var c=Rb(a);return!b[c]?b[c]=1:0}function d(a,b){if(eb){var c=fb[a];if(c&&!b)return c}if(c=gb[a])return c;var c=a.charAt(0),e=-1==a.indexOf(" ");0<=a.indexOf("#")&&
e&&(b=i);if(eb&&!b&&-1==">~+".indexOf(c)&&(!B||-1==a.indexOf(":"))&&!(hb&&0<=a.indexOf("."))&&-1==a.indexOf(":contains")&&-1==a.indexOf("|=")){var g=0<=">~+".indexOf(a.charAt(a.length-1))?a+" *":a;return fb[a]=function(b){try{if(!(9==b.nodeType||e))throw"";var c=b.querySelectorAll(g);B?c.yb=i:c.ha=i;return c}catch(f){return d(a,i)(b)}}}var q=a.split(/\s*,\s*/);return gb[a]=2>q.length?f(a):function(a){for(var b=0,c=[],d;d=q[b++];)c=c.concat(f(d)(a));return c}}function f(a){var b=ib(ha(a));if(1==b.length){var c=
e(b[0]);return function(a){if(a=c(a,[]))a.ha=i;return a}}return function(a){for(var a=X(a),c,d,f=b.length,db,g,Ea=0;Ea<f;Ea++){g=[];c=b[Ea];d=a.length-1;0<d&&(db={},g.ha=i);d=e(c);for(var q=0;c=a[q];q++)d(c,g,db);if(!g.length)break;a=g}return g}}function e(a){var b=jb[a.L];if(b)return b;var c=a.$a,c=c?c.ia:"",d=l(a,{J:1}),e="*"==a.h,f=document.getElementsByClassName;if(c)f={J:1},e&&(f.h=1),d=l(a,f),"+"==c?b=k(d):"~"==c?b=j(d):">"==c&&(b=g(d));else if(a.id)d=!a.bb&&e?V:l(a,{J:1,id:1}),b=function(b,
c){var e;e=b?new K(9==b.nodeType?b:b.ownerDocument||b.document):Xa||(Xa=new K);var f=a.id;if(f=(e=y(f)?e.va.getElementById(f):f)&&d(e))if(!(f=9==b.nodeType)){for(f=e.parentNode;f&&!(f==b);)f=f.parentNode;f=!!f}if(f)return X(e,c)};else if(f&&/\{\s*\[native code\]\s*\}/.test(""+f)&&a.s.length&&!hb)var d=l(a,{J:1,s:1,id:1}),q=a.s.join(" "),b=function(a,b){for(var c=X(0,b),e,f=0,g=a.getElementsByClassName(q);e=g[f++];)d(e,a)&&c.push(e);return c};else!e&&!a.bb?b=function(b,c){for(var d=X(0,c),e,f=0,g=
b.getElementsByTagName(a.wa());e=g[f++];)d.push(e);return d}:(d=l(a,{J:1,h:1,id:1}),b=function(b,c){for(var e=X(0,c),f,g=0,Qb=b.getElementsByTagName(a.wa());f=Qb[g++];)d(f,b)&&e.push(f);return e});return jb[a.L]=b}function g(a){a=a||V;return function(b,d,e){for(var f=0,g=b[kb];b=g[f++];)Y(b)&&(!e||c(b,e))&&a(b,f)&&d.push(b);return d}}function j(a){return function(b,d,e){for(b=b[Z];b;){if(Y(b)){if(e&&!c(b,e))break;a(b)&&d.push(b)}b=b[Z]}return d}}function k(a){return function(b,d,e){for(;b=b[Z];)if(!oa||
na(b)){(!e||c(b,e))&&a(b)&&d.push(b);break}return d}}function l(a,b){if(!a)return V;var b=b||{},c=n;b.J||(c=T(c,na));b.h||"*"!=a.h&&(c=T(c,function(b){return b&&b.tagName==a.wa()}));b.s||I(a.s,function(a,b){var d=RegExp("(?:^|\\s)"+a+"(?:\\s|$)");c=T(c,function(a){return d.test(a.className)});c.count=b});b.D||I(a.D,function(a){var b=a.name;Fa[b]&&(c=T(c,Fa[b](b,a.value)))});b.$||I(a.$,function(a){var b,d=a.ta;a.type&&lb[a.type]?b=lb[a.type](d,a.xa):d.length&&(b=Sb(d));b&&(c=T(c,b))});b.id||a.id&&
(c=T(c,function(b){return!!b&&b.id==a.id}));c||"default"in b||(c=V);return c}function r(a){return q(a)%2}function m(a){return!(q(a)%2)}function q(a){var b=a.parentNode,c=0,d=b[kb],e=a._i||-1,f=b._l||-1;if(!d)return-1;d=d.length;if(f==d&&0<=e&&0<=f)return e;b._l=d;e=-1;for(b=b.firstElementChild||b.firstChild;b;b=b[Z])Y(b)&&(b._i=++c,a===b&&(e=c));return e}function u(a){for(;a=a[Z];)if(Y(a))return p;return i}function w(a){for(;a=a[Tb];)if(Y(a))return p;return i}function G(a,b){return!a?"":"class"==
b?a.className||"":"for"==b?a.htmlFor||"":"style"==b?a.style.cssText||"":(S?a.getAttribute(b):a.getAttribute(b,2))||""}function na(a){return 1==a.nodeType}function T(a,b){return!a?b:!b?a:function(){return a.apply(window,arguments)&&b.apply(window,arguments)}}function ib(a){function b(){0<=u&&(o.id=c(u,s).replace(/\\/g,""),u=-1);if(0<=l){var a=l==s?n:c(l,s);0>">~+".indexOf(a)?o.h=a:o.ia=a;l=-1}0<=j&&(o.s.push(c(j+1,s).replace(/\\/g,"")),j=-1)}function c(b,d){return ha(a.slice(b,d))}for(var a=0<=">~+".indexOf(a.slice(-1))?
a+" * ":a+" ",d=[],e=-1,f=-1,g=-1,q=-1,j=-1,u=-1,l=-1,m="",k="",r,s=0,G=a.length,o=n,w=n;m=k,k=a.charAt(s),s<G;s++)if("\\"!=m)if(o||(r=s,o={L:n,D:[],$:[],s:[],h:n,ia:n,id:n,wa:function(){return S?this.Hb:this.h}},l=s),0<=e)if("]"==k){w.ta?w.xa=c(g||e+1,s):w.ta=c(e+1,s);if((e=w.xa)&&('"'==e.charAt(0)||"'"==e.charAt(0)))w.xa=e.slice(1,-1);o.$.push(w);w=n;e=g=-1}else"="==k&&(g=0<="|~^$*".indexOf(m)?m:"",w.type=g+k,w.ta=c(e+1,s-g.length),g=s+1);else 0<=f?")"==k&&(0<=q&&(w.value=c(f+1,s)),q=f=-1):"#"==
k?(b(),u=s+1):"."==k?(b(),j=s):":"==k?(b(),q=s):"["==k?(b(),e=s,w={}):"("==k?(0<=q&&(w={name:c(q+1,s),value:n},o.D.push(w)),f=s):" "==k&&m!=k&&(b(),0<=q&&o.D.push({name:c(q+1,s)}),o.bb=o.D.length||o.$.length||o.s.length,o.$b=o.L=c(r,s),o.Hb=o.h=o.ia?n:o.h||"*",o.h&&(o.h=o.h.toUpperCase()),d.length&&d[d.length-1].ia&&(o.$a=d.pop(),o.L=o.$a.L+" "+o.L),d.push(o),o=n);return d}function X(a,b){var c=b||[];a&&c.push(a);return c}var hb=D&&"BackCompat"==document.compatMode,kb=document.firstChild.children?
"children":"childNodes",S=p,lb={"*=":function(a,b){return function(c){return 0<=G(c,a).indexOf(b)}},"^=":function(a,b){return function(c){return 0==G(c,a).indexOf(b)}},"$=":function(a,b){return function(c){c=" "+G(c,a);return c.lastIndexOf(b)==c.length-b.length}},"~=":function(a,b){var c=" "+b+" ";return function(b){return 0<=(" "+G(b,a)+" ").indexOf(c)}},"|=":function(a,b){b=" "+b;return function(c){c=" "+G(c,a);return c==b||0==c.indexOf(b+"-")}},"=":function(a,b){return function(c){return G(c,a)==
b}}},oa="undefined"==typeof document.firstChild.nextElementSibling,Z=!oa?"nextElementSibling":"nextSibling",Tb=!oa?"previousElementSibling":"previousSibling",Y=oa?na:V,Fa={checked:function(){return function(a){return a.checked||a.attributes.checked}},"first-child":function(){return w},"last-child":function(){return u},"only-child":function(){return function(a){return!w(a)||!u(a)?p:i}},empty:function(){return function(a){for(var b=a.childNodes,a=a.childNodes.length-1;0<=a;a--){var c=b[a].nodeType;
if(1===c||3==c)return p}return i}},contains:function(a,b){var c=b.charAt(0);if('"'==c||"'"==c)b=b.slice(1,-1);return function(a){return 0<=a.innerHTML.indexOf(b)}},not:function(a,b){var c=ib(b)[0],d={J:1};"*"!=c.h&&(d.h=1);c.s.length||(d.s=1);var e=l(c,d);return function(a){return!e(a)}},"nth-child":function(a,b){if("odd"==b)return r;if("even"==b)return m;if(-1!=b.indexOf("n")){var c=b.split("n",2),d=c[0]?"-"==c[0]?-1:parseInt(c[0],10):1,e=c[1]?parseInt(c[1],10):0,f=0,g=-1;0<d?0>e?e=e%d&&d+e%d:0<
e&&(e>=d&&(f=e-e%d),e%=d):0>d&&(d*=-1,0<e&&(g=e,e%=d));if(0<d)return function(a){a=q(a);return a>=f&&(0>g||a<=g)&&a%d==e};b=e}var j=parseInt(b,10);return function(a){return q(a)==j}}},Sb=B?function(a){var b=a.toLowerCase();"class"==b&&(a="className");return function(c){return S?c.getAttribute(a):c[a]||c[b]}}:function(a){return function(b){return b&&b.getAttribute&&b.hasAttribute(a)}},jb={},gb={},fb={},eb=!!document.querySelectorAll&&(!D||H("526")),F=0,Rb=B?function(a){return S?a.getAttribute("_uid")||
a.setAttribute("_uid",++F)||F:a.uniqueID}:function(a){return a._uid||(a._uid=++F)};a.D=Fa;return a}();aa("goog.dom.query",Ib);aa("goog.dom.query.pseudos",Ib.D);(function(){var a;annotorious.k={};annotorious.k.g={};annotorious.k.g.o={};a=annotorious.n;annotorious.k.g.o=function(b,c,d){this.w=b;this.Q=c;this.f=d;this.Y=[];this.C=[];this.i=this.w.getContext("2d");this.d=n;this.H=i;this.P=n;this.Ma=p;var f=this;R(this.w,a.kb,function(a){f.H?f.ub(a):f.P=a});W(d,annotorious.a.b.G,function(){delete f.d;f.H=i});W(d,annotorious.a.b.W,function(){var a,b;if(!f.H&&f.P){a=annotorious.a.U(f.P);b=a.x;a=a.y;var c=f.d;f.d=f.Ba(b,a);f.H=i;c!=f.d?(f.S(),f.f.fireEvent(annotorious.a.b.jb,
{annotation:c,ya:f.P}),f.f.fireEvent(annotorious.a.b.Ea,{annotation:f.d,ya:f.P})):f.d&&f.Q.ua()}else f.S()})};annotorious.k.g.o.prototype.Ta=function(a){this.Y.push(a);var c=a.V[0];if(c.ac!=annotorious.shape.pb.lb)var d=this,c=annotorious.shape.transform(c,function(a){return d.f.Cb(a)});this.C[z(a)]=c;this.Z(c)};annotorious.k.g.o.prototype.Ib=function(a){a==this.d&&delete this.d;Qa(this.Y,a);delete this.C[z(a)];this.S()};annotorious.k.g.o.prototype.Za=function(){this.d=h;this.Q.ka();this.S()};annotorious.k.g.o.prototype.Ba=
function(a,c){var d=this.xb(a,c);if(0<d.length)return d[0]};annotorious.k.g.o.prototype.xb=function(a,c){var d=[],f=this;I(this.Y,function(e){annotorious.shape.Gb(f.C[z(e)],a,c)&&d.push(e)});Va(d,function(a,b){return annotorious.shape.size(a.V[0])>annotorious.shape.size(b.V[0])});return d};annotorious.k.g.o.prototype.ub=function(a){var c=annotorious.a.U(a);(c=this.Ba(c.x,c.y))?(this.Ma=p,this.d?this.d!=c&&(this.H=p,this.Q.ka()):(this.d=c,this.S(),this.f.fireEvent(annotorious.a.b.Ea,{annotation:this.d,
ya:a}))):!this.Ma&&this.d&&(this.H=p,this.Q.ka())};annotorious.k.g.o.prototype.Z=function(a,c){var d=Pa(this.f.Db(),function(c){return c.Fb()==a.type});d?d.Bb(this.i,a,c):console.log("WARNING unsupported shape type: "+a.type)};annotorious.k.g.o.prototype.S=function(){this.i.clearRect(0,0,this.w.width,this.w.height);var a=this;I(this.Y,function(c){a.Z(a.C[z(c)])});if(this.d){var c=this.C[z(this.d)];this.Z(c,i);c=annotorious.shape.Wa(c);this.Q.show(this.d,{x:c.x,y:c.y+c.height+5})}}})();function Jb(a,b,c){y(b)?Kb(a,c,b):bb(b,fa(Kb,a))}function Kb(a,b,c){a.style[ra(c)]=b}function Lb(a,b,c){var d=C&&(va||Ca)&&H("1.9");a.style.left=Mb(b,d);a.style.top=Mb(c,d)}function Nb(a,b,c){if(c==h)throw Error("missing height argument");a.style.width=Mb(b,i);a.style.height=Mb(c,i)}function Mb(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function Ob(a,b){var c=a.style;"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*b+")")}function Pb(a,b){a.style.display=b?"":"none"};(function(){var a=annotorious.n;annotorious.l={};annotorious.l.Da={};annotorious.l.Da=function(b,c){function d(a){var d=p,e=a.relatedTarget||p;e||(d=i);tb(g,e)&&(d=i);var f;if(f=tb(c.editor.element[0],e))f=c.editor.annotation,f=!f?p:f.url==b.src;f&&(d=i);tb(c.viewer.element[0],e)&&k.ea()&&(d=i);a.r&&a.r.touches&&(d=p);return d}var f=annotorious.z.T(c.element[0].firstChild),e=new annotorious.a.Ca,g=pb("div","yuma-annotationlayer");Jb(g,"position","relative");Nb(g,b.width,b.height);sb(g,b);g.appendChild(b);
var j=ub(annotorious.B.g.canvas,{width:b.width,height:b.height});g.appendChild(j);var k=new annotorious.l.u(b,e,c,f),l=ub(annotorious.B.g.canvas,{width:b.width,height:b.height});annotorious.n.ca||Pb(l,p);g.appendChild(l);var r=new annotorious.k.g.o(j,k,e),m=new annotorious.plugins.selection.m;m.K(l,e,r,k);new annotorious.hint.N(e,g);e.ib=function(a){return a};e.Cb=function(a){return a};e.Db=function(){return[m]};R(g,a.Ga,function(a){d(a)||e.fireEvent(annotorious.a.b.O)});R(g,a.Fa,function(a){d(a)||
e.fireEvent(annotorious.a.b.G)});k.wb(function(a){d(a)||e.fireEvent(annotorious.a.b.O)});k.vb(function(a){d(a)||e.fireEvent(annotorious.a.b.G)});R(annotorious.n.ca?l:j,a.Nb,function(a){var b=annotorious.a.U(a,j);a.preventDefault();Pb(l,i);r.Za();m.Jb(b.x,b.y)});W(e,annotorious.a.b.O,function(){c.clearViewerHideTimer();Ob(j,1)});W(e,annotorious.a.b.G,function(){Ob(j,0.4)});W(e,annotorious.a.b.Ia,function(a){var d={url:b.src,V:[a.shape]};c.publish("beforeAnnotationCreated",d);var e=annotorious.z.T(b),
g=a.shape.e,a=g.x+e.left-f.left+16,e=g.y+g.height+e.top+window.pageYOffset-f.top+5;c.showEditor(d,{top:window.pageYOffset-f.top,left:0});Lb(c.editor.element[0],a,e)});W(e,annotorious.a.b.Ha,function(){annotorious.n.ca||Pb(l,p);m.Aa()});c.viewer.on("edit",function(a){if(a.url==b.src){Pb(l,i);r.Za();var d=annotorious.z.T(b),e=a.V[0].e,a=e.x+d.left-f.left+16,d=e.y+e.height+d.top-f.top+window.pageYOffset+5;Lb(c.editor.element[0],0,window.pageYOffset-f.top);c.editor.show();Lb(c.editor.element[0],a,d)}});
c.subscribe("annotationCreated",function(a){a.url==b.src&&(m.Aa(),a.url==b.src&&r.Ta(a))});c.subscribe("annotationsLoaded",function(a){I(a,function(a){a.url==b.src&&r.Ta(a)})});c.subscribe("annotationDeleted",function(a){a.url==b.src&&r.Ib(a);e.fireEvent(annotorious.a.b.W)});c.subscribe("annotationEditorHidden",function(){annotorious.n.ca||Pb(l,p);m.Aa();e.fireEvent(annotorious.a.b.W)})};window.Annotator.Plugin.AnnotoriousImagePlugin=function(){function a(b){this.qb=b}a.prototype.pluginInit=function(){var a=
this;I(this.qb.getElementsByTagName("img"),function(b){new annotorious.l.Da(b,a.annotator)})};return a}()})();(function(){var a=annotorious.n;annotorious.l.u={};annotorious.l.u=function(b,c,d,f){this.La=b;this.rb=c;this.p=d;this.oa=f;this.pa=p;this.Qa=[];this.Pa=[];var e=this;R(this.p.viewer.element[0],a.Ga,function(a){e.ea()&&(e.ua(),I(e.Qa,function(b){b(a)}))});R(this.p.viewer.element[0],a.Fa,function(a){e.ea()&&(d.clearViewerHideTimer(),e.ka(),I(e.Pa,function(b){b(a)}))})};annotorious.l.u.prototype.ea=function(){var a=this.p.viewer.annotations;return!a||1>a.length?p:a[0].url==this.La.src};annotorious.l.u.prototype.wb=
function(a){this.Qa.push(a)};annotorious.l.u.prototype.vb=function(a){this.Pa.push(a)};annotorious.l.u.prototype.ka=function(){if(!(0<=Oa(Za(this.p.viewer.element[0]),"annotator-hide"))&&(this.pa=p,!this.R)){var a=this;this.R=window.setTimeout(function(){a.rb.fireEvent(annotorious.a.b.W);!a.pa&&a.ea()&&($a(a.p.viewer.element[0],"annotator-hide"),a.p.viewer.annotations=[],delete a.R)},300)}};annotorious.l.u.prototype.ua=function(){this.pa=i;this.R&&(window.clearTimeout(this.R),delete this.R)};annotorious.l.u.prototype.show=
function(a,c){ab(this.p.viewer.element[0],"annotator-hide");var d=annotorious.z.T(this.La);Lb(this.p.viewer.element[0],0,window.pageYOffset-this.oa.top);this.p.viewer.load([a]);Lb(this.p.viewer.element[0],d.left-this.oa.left+c.x+16,d.top+window.pageYOffset-this.oa.top+c.y);this.ua()}})();(function(){var a=annotorious.n;annotorious.plugins={};annotorious.plugins.selection={};annotorious.plugins.selection.m={};annotorious.plugins.selection.m=function(){};annotorious.plugins.selection.m.prototype.K=function(a,c,d,f){this.w=a;this.f=c;this.eb=f;this.i=a.getContext("2d");this.i.lineWidth=1;this.qa=p;this.viewer=d};annotorious.plugins.selection.m.prototype.na=function(){var b=this,c=this.w;this.sa=R(c,a.kb,function(a){var f=annotorious.a.U(a,c);a.preventDefault();b.qa&&(b.q={x:f.x,y:f.y},
b.i.clearRect(0,0,c.width,c.height),a=b.q.x-b.c.x,f=b.q.y-b.c.y,b.i.strokeStyle="#000000",b.i.strokeRect(b.c.x+0.5,b.c.y+0.5,a,f),b.i.strokeStyle="#ffffff",0<a&&0<f?b.i.strokeRect(b.c.x+1.5,b.c.y+1.5,a-2,f-2):0<a&&0>f?b.i.strokeRect(b.c.x+1.5,b.c.y-0.5,a-2,f+2):0>a&&0>f?b.i.strokeRect(b.c.x-0.5,b.c.y-0.5,a+2,f+2):b.i.strokeRect(b.c.x-0.5,b.c.y+1.5,a+2,f-2))});this.Oa=R(c,a.Rb,function(a){var f=annotorious.a.U(a,c),e;e=b.Eb();a=a.r?a.r:a;b.qa=p;if(e)b.f.fireEvent(annotorious.a.b.Ia,{ya:a,shape:e,bc:b.Xa()});
else if(b.f.fireEvent(annotorious.a.b.Ha),annotorious.n.ca&&(a=b.viewer.Ba(f.x,f.y)))e=b.viewer.C[z(a)],e=annotorious.shape.Wa(e),b.eb.show(a,{x:e.x,y:e.y+e.height+5})})};annotorious.plugins.selection.m.prototype.Ja=function(){this.sa&&(U(this.sa),delete this.sa);this.Oa&&(U(this.Oa),delete this.Sb)};annotorious.plugins.selection.m.prototype.Fb=function(){return annotorious.shape.j.v};annotorious.plugins.selection.m.prototype.Jb=function(a,c){var d={x:a,y:c};this.qa=i;this.na(d);this.c=new annotorious.shape.A.mb(a,
c);this.f.fireEvent(annotorious.a.b.ob,{offsetX:a,offsetY:c});Jb(document.body,"-webkit-user-select","none")};annotorious.plugins.selection.m.prototype.Aa=function(){this.Ja();this.i.clearRect(0,0,this.w.width,this.w.height);Jb(document.body,"-webkit-user-select","auto");delete this.q};annotorious.plugins.selection.m.prototype.Eb=function(){if(this.q){var a=this.Xa(),c=this.f.ib({x:a.left,y:a.top}),a=this.f.ib({x:a.right-1,y:a.bottom-1});return new annotorious.shape.ma(annotorious.shape.j.v,new annotorious.shape.A.la(c.x,
c.y,a.x-c.x,a.y-c.y))}};annotorious.plugins.selection.m.prototype.Xa=function(){var a,c;this.q.x>this.c.x?(a=this.q.x,c=this.c.x):(a=this.c.x,c=this.q.x);var d,f;this.q.y>this.c.y?(d=this.c.y,f=this.q.y):(d=this.q.y,f=this.c.y);return{top:d,right:a,bottom:f,left:c}};annotorious.plugins.selection.m.prototype.Bb=function(a,c,d){if(c.type==annotorious.shape.j.v){var f;d?(d="#fff000",f=1.2):(d="#ffffff",f=1);c=c.e;a.strokeStyle="#000000";a.lineWidth=f;a.strokeRect(c.x+0.5,c.y+0.5,c.width+1,c.height+1);
a.strokeStyle=d;a.strokeRect(c.x+1.5,c.y+1.5,c.width-1,c.height-1)}}})();annotorious.annotation={};annotorious.annotation.Mb=function(a,b,c){this.src=a;this.text=b;this.V=[c];this.context=document.URL};annotorious.z={};annotorious.z.T=function(a){for(var b=0,c=0;a&&!isNaN(a.offsetLeft)&&!isNaN(a.offsetTop);)b+=a.offsetLeft-a.scrollLeft,c+=a.offsetTop-a.scrollTop,a=a.offsetParent;return{top:c,left:b}};annotorious.z.Zb=function(a){for(var b=a.offsetTop,c=a.offsetLeft,d=a.offsetWidth,f=a.offsetHeight;a.offsetParent;)a=a.offsetParent,b+=a.offsetTop,c+=a.offsetLeft;return b<window.pageYOffset+window.innerHeight&&c<window.pageXOffset+window.innerWidth&&b+f>window.pageYOffset&&c+d>window.pageXOffset};
annotorious.z.Tb=function(a){if("function"==typeof window.onload){var b=window.onload;window.onload=function(){a();b()}}else window.onload=a};annotorious.a={};annotorious.a.Ca=function(){this.I=[]};annotorious.a.U=function(a,b){var c=p,c=annotorious.z.T;return c=!a.offsetX||!a.offsetY&&a.r.changedTouches?{x:a.r.changedTouches[0].pageX-c(b).left,y:a.r.changedTouches[0].pageY-c(b).top}:{x:a.offsetX,y:a.offsetY}};annotorious.a.Vb=function(a,b){var c=document.createEvent(annotorious.n.Wb);c[annotorious.n.Yb](a,i,i,window);b.dispatchEvent(c)};function W(a,b,c){a.I[b]||(a.I[b]=[]);a.I[b].push(c)}
annotorious.a.Ca.prototype.fireEvent=function(a,b){var c=this.I[a];c&&I(c,function(a){a(b)})};annotorious.a.b={O:"onMouseOverItem",G:"onMouseOutOfItem",Ea:"onMouseOverAnnotation",jb:"onMouseOutOfAnnotation",ob:"onSelectionStarted",Ha:"onSelectionCanceled",Ia:"onSelectionCompleted",Qb:"onSelectionChanged",W:"beforePopupHide",Lb:"onAnnotationRemoved",Kb:"onAnnotationCreated"};(function(){var a=annotorious.n;annotorious.hint={};annotorious.hint.N=function(a,c){var d=this;this.element=ub(annotorious.B.hint);this.f=a;this.Na=Ib(".annotorious-hint-msg",this.element)[0];this.Ka=Ib(".annotorious-hint-icon",this.element)[0];this.Sa=function(){d.show()};this.Ra=function(){d.da()};this.na();this.da();c.appendChild(this.element)};annotorious.hint.N.prototype.na=function(){var b=this;this.tb=R(this.Ka,a.Ga,function(){b.show();window.clearTimeout(b.ra)});this.sb=R(this.Ka,a.Fa,function(){b.da()});
W(this.f,annotorious.a.b.O,this.Sa);W(this.f,annotorious.a.b.G,this.Ra)};annotorious.hint.N.prototype.Ja=function(){U(this.tb);U(this.sb);var a=this.f.I[annotorious.a.b.O];a&&Qa(a,this.Sa);(a=this.f.I[annotorious.a.b.G])&&Qa(a,this.Ra)};annotorious.hint.N.prototype.show=function(){window.clearTimeout(this.ra);Ob(this.Na,0.8);var a=this;this.ra=window.setTimeout(function(){a.da()},3E3)};annotorious.hint.N.prototype.da=function(){window.clearTimeout(this.ra);Ob(this.Na,0)}})();B&&H(8);"ScriptEngine"in v&&"JScript"==v.ScriptEngine()&&(v.ScriptEngineMajorVersion(),v.ScriptEngineMinorVersion(),v.ScriptEngineBuildVersion());function Ub(a){return"object"===typeof a&&a&&0===a.Ub?a.content:(""+a).replace(Vb,Wb)}var Xb={"\x00":"&#0;",'"':"&quot;","&":"&amp;","'":"&#39;","<":"&lt;",">":"&gt;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\u000c":"&#12;","\r":"&#13;"," ":"&#32;","-":"&#45;","/":"&#47;","=":"&#61;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Wb(a){return Xb[a]}var Vb=/[\x00\x22\x26\x27\x3c\x3e]/g;annotorious.B={};annotorious.B.hint=function(){return'<div class="annotorious-hint" style="white-space:nowrap; position:absolute; top:0px; left:0px; pointer-events:none;"><div class="annotorious-hint-msg annotorious-opacity-fade">Click and Drag to Annotate</div><div class="annotorious-hint-icon" style="pointer-events:auto"></div></div>'};annotorious.B.eb=function(){return'<div class="annotorious-popup" style="position:absolute;"><a class="annotorious-popup-button annotorious-popup-button-delete" title="Delete" href="javascript:void(0);">DELETE</a><span class="annotorious-popup-text"></span></div>'};
annotorious.B.Xb=function(){return'<div class="annotorious-editor" style="position:absolute;"><form><textarea class="annotorious-editor-text" placeholder="Add a Comment..."></textarea><div class="annotorious-editor-button-container"><a class="annotorious-editor-button annotorious-editor-button-cancel" href="javascript:void(0);">Cancel</a><a class="annotorious-editor-button annotorious-editor-button-save" href="javascript:void(0);">Save</a></div></form></div>'};annotorious.B.g={};annotorious.B.g.canvas=function(a){return'<canvas class="annotorious-opacity-fade" style="position:absolute; top:0px; left:0px; width:'+Ub(a.width)+"px; height:"+Ub(a.height)+'px;" width="'+Ub(a.width)+'" height="'+Ub(a.height)+'"></canvas>'};
